schemaVersion: 2.1.0
metadata:
  name: openshift_test
components:
  - name: python
    container:
      image: quay.io/apinyk/mytest
      env:
        - name: VSCODE_DEFAULT_WORKSPACE
          value: /projects/openshift-test/.code-workspace
